/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cnpm_fe;

import models.HocSinh;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MIXI_COMPUTER
 */
public class SuaHocSinh extends JFrame {
    private HocSinh hocSinh;

    /**
     * Creates new form Them_hoc_sinh
     */
    public SuaHocSinh(HocSinh hocSinh) {
        this.hocSinh = hocSinh;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        lbThemHocSinh = new JLabel();
        lbLop = new JLabel();
        tfLop = new JTextField();
        btnLuu = new JButton();
        btnHuy = new JButton();
        lbThanhTich = new JLabel();
        cbThanhTich = new JComboBox<>();
        lbTruong = new JLabel();
        tfTruong = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        lbThemHocSinh.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbThemHocSinh.setForeground(new Color(0, 102, 102));
        lbThemHocSinh.setText("Sửa thông tin học sinh");

        lbLop.setForeground(new Color(0, 102, 102));
        lbLop.setText("Lớp");
        tfLop.setText(hocSinh.getLop());

        btnLuu.setBackground(new Color(0, 51, 51));
        btnLuu.setForeground(new Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new Color(102, 0, 0));
        btnHuy.setForeground(new Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        btnHuy.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lbThanhTich.setForeground(new Color(0, 102, 102));
        lbThanhTich.setText("Thành tich");

        lbTruong.setForeground(new Color(0, 102, 102));
        lbTruong.setText("Trường ");
        tfTruong.setText(hocSinh.getTruong());

        int index = switch (hocSinh.getThanhTich()) {
            case "Giỏi" -> 0;
            case "Tiên tiến" -> 1;
            case "Trung bình" -> 2;
          default -> 0;
        };
        cbThanhTich.setModel(new DefaultComboBoxModel<>(
            new String[] { "Giỏi", "Tiên tiến", "Trung bình"}));
        cbThanhTich.setSelectedIndex(index);



        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbLop)
                    .addComponent(lbThanhTich)
                    .addComponent(lbTruong))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbThemHocSinh, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfLop)
                    .addComponent(cbThanhTich)
                    .addComponent(tfTruong))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnLuu)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHuy)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThemHocSinh)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLop)
                            .addComponent(tfLop, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbTruong))
                    .addComponent(tfTruong, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbThanhTich)
                    .addComponent(cbThanhTich, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(132, 132, 132))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenHocSinhActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tfTenHocSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenHocSinhActionPerformed

    private void btnLuuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnHuyActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tfMaHoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tfMaHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaHoActionPerformed

    private void btnLuuMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        if(tfLop.getText().isEmpty() || tfTruong.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin");
        } else {
            hocSinh.setThanhTich(cbThanhTich.getSelectedItem().toString());
            hocSinh.setLop(tfLop.getText());
            hocSinh.setTruong(tfTruong.getText());
            boolean status = hocSinh.editRow();
            if (status) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa không thành công");
            }
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuaHocSinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SuaHocSinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SuaHocSinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SuaHocSinh.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLuu;
    private JButton btnHuy;
    private JPanel jPanel1;
    private JLabel lbThanhTich;
    private JLabel lbLop;
    private JLabel lbThemHocSinh;
    private JLabel lbTruong;
    private JComboBox<String> cbThanhTich;
    private JTextField tfLop;
    private JTextField tfTruong;
    // End of variables declaration//GEN-END:variables
}
