/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cnpm_fe;

import models.DipTangThuong;
import textHandle.ReadMapFromText;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author MIXI_COMPUTER
 */
public class ThemDipThuong extends javax.swing.JFrame {
    private DipTangThuong dipTangThuong;
    /**
     * Creates new form Them_dip_thuong
     */
    public ThemDipThuong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        lbThemThongTin = new javax.swing.JLabel();
        lbThanhTich = new javax.swing.JLabel();
        cbThanhTich = new javax.swing.JComboBox<>();
        lbDipThuong = new javax.swing.JLabel();
        tfDipThuong = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lbChiTiet = new JLabel();
        taChiTiet = new JTextArea();
        taLuuY = new JTextArea();
        spLuuY = new JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(600, 700));

        lbThemThongTin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbThemThongTin.setForeground(new java.awt.Color(0, 102, 102));
        lbThemThongTin.setText("Thêm thông tin dịp thưởng");

        lbThanhTich.setForeground(new java.awt.Color(0, 102, 102));
        lbThanhTich.setText("Thành tích");

        cbThanhTich.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] { "Giỏi", "Tiên tiến", "Trung bình", ""}));

        lbDipThuong.setForeground(new java.awt.Color(0, 102, 102));
        lbDipThuong.setText("Dịp thưởng");

        lbChiTiet.setForeground(new java.awt.Color(0, 102, 102));
        lbChiTiet.setText("Chi tiết");

        btnLuu.setBackground(new java.awt.Color(0, 51, 51));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(102, 0, 0));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        taChiTiet.setColumns(20);
        taChiTiet.setRows(10);

        taLuuY.setColumns(10);
        taLuuY.setForeground(new java.awt.Color(0, 102, 102));
        taLuuY.setRows(5);
        taLuuY.setText("- Mục dịp thưởng phải được điền với định dạng: \n" +
            "   + \"năm học + học kỳ\" cho việc tặng thưởng cuối năm học \n" +
            "(Ví dụ: 20231)\n" +
            "   + \"tên dịp + năm\" cho việc tặng thưởng dịp lễ \n" +
            "(Ví dụ: Trung thu 2023)\n" +
            "- Mục thành tích thì để trống nếu dịp thưởng là dịp lễ\n" +
            "- Mục chi tiết phải được điền với định dạng: \n" +
            "   + \"tên quà: + giá tiền\", các món quà ngăn cách bởi dấu ','\n" +
            "(Ví dụ: 6 goi bim bim: 100000, 5 cuon vo: 50000");
        spLuuY.setViewportView(taLuuY);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDipThuong)
                            .addComponent(lbThanhTich)
                            .addComponent(lbChiTiet)
                        )
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, true)
                            .addComponent(lbThemThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbThanhTich)
                            .addComponent(tfDipThuong)
                            .addComponent(taChiTiet)
                            .addComponent(spLuuY)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnLuu)
                        .addGap(290, 290, 290)
                        .addComponent(btnHuy)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThemThongTin)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThanhTich)
                    .addComponent(cbThanhTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDipThuong)
                    .addComponent(tfDipThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbChiTiet))
                .addGap(44, 44, 44)
                .addComponent(spLuuY)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfThanhTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThanhTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThanhTichActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        String dipThuong = tfDipThuong.getText();
        String thanhTich = cbThanhTich.getSelectedItem().toString();
        String chiTiet = taChiTiet.getText();
        if(dipThuong.isEmpty() || chiTiet.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng điền đủ thông tin");
            return;
        }
        if (!(dipThuong.matches("^\\d{5}$")
            || dipThuong.matches("^.+ \\d{4}$"))) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đúng định dạng học kỳ");
            return;
        }
        if (Character.isDigit(dipThuong.charAt(0)) && thanhTich.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thành tích khi thưởng cuối năm học");
            return;
        }

        if (!Character.isDigit(dipThuong.charAt(0)) && !thanhTich.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng để trống mục thành tích khi thưởng dịp lễ");
            return;
        }

        if (!chiTiet.matches("^\\s*(?:\\S+(?:\\s+\\S+)*\\s*:\\s*\\d+\\s*,\\s*)*\\S+(?:\\s+\\S+)*\\s*:\\s*\\d+\\s*$")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đúng định dạng chi tiết");
            return;
        }

        dipTangThuong = new DipTangThuong(thanhTich, dipThuong,
            ReadMapFromText.readMapFromText(chiTiet));
        boolean status = dipTangThuong.addNewRow();
        if (status) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Thành tích và dịp thưởng bị trùng");
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDipThuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDipThuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDipThuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDipThuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemDipThuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDipThuong;
    private javax.swing.JLabel lbChiTiet;
    private javax.swing.JLabel lbThanhTich;
    private javax.swing.JLabel lbThemThongTin;
    private javax.swing.JTextField tfDipThuong;
    private javax.swing.JTextArea taChiTiet;
    private javax.swing.JComboBox<String> cbThanhTich;
    private javax.swing.JTextArea taLuuY;
    private javax.swing.JScrollPane spLuuY;
    // End of variables declaration//GEN-END:variables
}
